# Generated by Django 4.2.1 on 2023-06-13 10:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (auto)')),
            ],
            options={
                'verbose_name': 'Post Tag',
                'verbose_name_plural': 'Post Tags',
            },
        ),
        migrations.CreateModel(
            name='WorkTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (auto)')),
            ],
            options={
                'verbose_name': 'Work Tag',
                'verbose_name_plural': 'Work Tags',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (auto)')),
                ('short_desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Short Description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('github_link', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='home.worktags')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['-time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (auto)')),
                ('short_desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Short Description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='home.posttags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
